[package]
name = "auftritt"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
maxminddb = "0.17"
r2d2 = "0.8.9"
serde = { version = "1.0", features = ["derive"] }